export const COURSE_NAMES = {
  // 1st Semester
  "ENG 1101": "English I",
  "CSE 1211": "Discrete Mathematics",
  "PHY 1201": "Physics I (Heat and Thermodynamics, Properties of Matters, Waves and Oscillations)",
  "CSE 1111": "Introduction to Computers",
  // 2nd Semester
  "EEE 1111": "Electrical Engineering and Circuit Analysis",
  "EEE 1121": "Electrical Engineering and Circuit Analysis Lab Work",
  "CSE 1112": "Structured Programming Language",
  "CSE 1121": "Structured Programming Language Lab Works",
  "MATH 1101": "Mathematics I (Differential Calculus and Integral Calculus)",
  // 3rd Semester
  "MATH 2103": "Mathematics III (Matrices, Vectors & Coordinate Geometry)",
  "CSE 2263": "Algorithms Design & Analysis",
  "CSE 2264": "Algorithms Design & Analysis Lab Work",
  "CSE 2215": "Digital logic Design",
  "CSE 2265": "Digital Logic Design Lab Work",
  "CSE 2319": "Database Management System",
  "CSE 2367": "Database Management Systems Lab Work",
  // 4th Semester
  "MATH 2204": "Mathematics IV (Complex Variable & Laplace Transformation)",
  "CSE 2109": "Electronic Engineering",
  "CSE 2161": "Electronic Engineering Lab Work",
  "CSE 3168": "Numerical Methods",
  "CSE 3186": "Numerical Methods Lab work",
  "CSE 3124": "Microprocessor and Assembly Language",
  "CSE 3171": "Microprocessor and Assembly Language programming Lab Work",
  "CSE 2291": "Software Development II (Database Programming)",
  // 5th Semester
  "MATH 2305": "Mathematics V (Statistics and Probability)",
  "CSE 2317": "Digital Electronics & Pulse Technique",
  "CSE 2366": "Digital Electronics & Pulse Technique Lab Work",
  "CSE 3169": "Theory of Computation",
  "CSE 3170": "Computer Architecture",
  "CSE 3227": "Data Communication",
  // 6th Semester
  "CSE 3228": "Compiler Design",
  "CSE 3272": "Compiler Design Lab Work",
  "CSE 3331": "Operating System",
  "CSE 3373": "Operating System Lab Work",
  "CSE 3333": "Object-Oriented Programming II (Java)",
  "CSE 3374": "Object-Oriented Programming II Lab Work",
  "CSE 3226": "Mathematical Analysis for Computer Science",
  // 7th Semester
  "CSE 3230": "Software Engineering",
  "CSE 4136": "Computer Networks",
  "CSE 4176": "Computer Networks Lab Work",
  "CSE 4138": "Computer Peripherals and Interfacing",
  "CSE 4177": "Computer Peripherals and Interfacing Lab",
  "CSE 4349": "Management Information Systems",
  "CSE 4389": "Field Work (Industrial Training)",
  // 8th Semester
  "CSE 4278": "Computer Graphics and Multimedia System Design",
  "CSE 4288": "Computer Graphics Lab Work",
  "CSE 4241": "VLSI Design",
  "CSE 4279": "VLSI Design Lab Work",
  "CSE 3375": "Communication Engineering",
  "CSE 3292": "Software Development III (Web Programming)",
  "IPE 4101": "Industrial Management",
  "CSE 4000": "Project & Thesis",
  // 9th Semester
  "CSE 4355": "Artificial Intelligence & Expert Systems",
  // 10th Semester / Electives
  "CSE 4385": "Artificial Intelligence & Expert Systems Lab Work",
  "CSE 4351": "Image Processing & Computer Vision",
  "CSE 4383": "Image Processing & Computer Vision Lab Work",

  // Legacy/Old Curriculum Courses
  "CSE 1102": "Structured Programming Language",
  "CSE 1157": "Structured Programming Language Lab",
  "CSE 1205": "Electrical Engineering and Circuit Analysis",
  "CSE 1258": "Discrete Mathematics",
  "CSE 1259": "Electrical Engineering and Circuit Analysis Lab",
  "CSE 1290": "Software Development I",
  "CSE 1307": "Object-Oriented Programming I (C++)",
  "CSE 1360": "Object-Oriented Programming Lab",
  "ENG 1204": "English II (Advanced)",
  "MATH 1302": "Mathematics II",
  "PHY 1302": "Physics II (Electromagnetism, Optics, and Modern Physics)",
};
